default: &default
  adapter: postgresql
  encoding: unicode
  
development:
  adapter: postgresql
  encoding: unicode
  database: health_development
  username: health_graph
  password: root1234

test:
  adapter: postgresql
  encoding: unicode
  database: health_test
  username: health_graph
  password: root1234
 
production:
  adapter: postgresql
  encoding: unicode
  database: health_production
  username: health_graph
  password: root1234